### ISSUE TITLE
Android: Edit button - when tapped it closed out of the app

### ISSUE THREAD

**Issue by TabulaRasaDV** [TabulaRasaDV/TRDV-Escape#15]

**Comment by rossedwardsus** [comment]
Is this a bug?

**Comment by TabulaRasaDV** [comment]
I'm not sure! 




Get Outlook for Android







On Wed, Jul 22, 2020 at 11:54 AM -0400, "Ross Edwards" <notifications@github.com> wrote:















Is this a bug?

**Comment by rossedwardsus** [comment]
What i mean is the app actually crashing?
