### ISSUE TITLE
Send Codes / 911 Modal Buttons Don't Work

### ISSUE THREAD

**Issue by hmaskell** [TabulaRasaDV/TRDV-Escape#17]
> Tap send codes / text 911
> See modal
> buttons don't allow you to close the modal on Android (but they work in iOS)
ReactNative Modal library (maybe not included in the Android activity?)

Also no need for Cancel button in the Send Codes modal

**Comment by riya-kumari** [comment]
Problem : imported TouchableOpacity from "react-native-gesture-handler"
Solution : imported TouchableOpacity from "react-native"
