### ISSUE TITLE
App unlocks if code is used in a calculation (5 + code = unlock)

### ISSUE THREAD

**Issue by hmaskell** [TabulaRasaDV/TRDV-Escape#24]
"5" "-" "222"
causes app to unlock.

I think this increases the likelihood of someone accidentally unlocking the app, and can't see it being particularly helpful to users to be able to unlock as a part of an equation.

I believe unlock should only occur when the code alone is entered and = is tapped.

**Comment by riya-kumari** [comment]
Doesn't matter much because the '222' I created is temporary. In reality, it would be a mix of numbers and emojis which the user will only be able to enter after a combination of buttons are pressed.
