### ISSUE TITLE
Send Codes: Code hint text is selectable but no action

### ISSUE THREAD

**Issue by hmaskell** [TabulaRasaDV/TRDV-Escape#4]
Steps to repro:

Send Codes > Tap the hint text until keyboard appears.
Text not editable, keyboard implies otherwise.

Perhaps codes should be editable here, and if so, the latest code for each contact should overwrite their existing code data.

**Comment by riya-kumari** [comment]
How should they edit the codes. Should it be like a popup?

**Comment by hmaskell** [comment]
I think I've changed my mind. I don't expect users to edit codes in an emergency, so no code editing in Send Codes for now.
