### ISSUE TITLE
Contacts: Individual contact card should have a View Contact state before an Edit Contact state

### ISSUE THREAD

**Issue by hmaskell** [TabulaRasaDV/TRDV-Escape#8]
Current flow: 
Contacts > Select a contact > Edit

Suggested flow:
Contacts > Select a contact > View contact > Edit

Edit state should be triggered by Edit button in top right or by tapping on any text
* Note: Edit Existing Contact screen has different elements from Add New Contact screen.

![View Contact](https://user-images.githubusercontent.com/23707057/87484143-4cd0e880-c5ea-11ea-84a8-c54fc756c1ad.png)
![Edit Contact](https://user-images.githubusercontent.com/23707057/87484141-4c385200-c5ea-11ea-8adf-6257b280f259.png)

**Comment by rossedwardsus** [comment]
One question i have about this is why is the user just viewing the contact?  Meaning as opposed to changing it?

**Comment by hmaskell** [comment]
The user would be viewing the contact to retrieve the information about the contact that they stored (the same way you view contacts in your regular contacts book.) They need the phone number of a trusted friend or they need to copy their address, but they didn’t want to store this info in plain sight as their abuser may monitor their connections with others.

They only edit this information when it becomes outdated or upon It’s first entry.

This feature would ideally evolve to include calling privately from within the app, and easily copying stored information somewhere down the line.

Sent from my iPhone

On Jul 16, 2020, at 6:01 AM, Ross Edwards <notifications@github.com> wrote:

﻿

One question i have about this is why is the user just viewing the contact? Meaning as opposed to changing it?
