### ISSUE TITLE
Contacts: Delete Contact

### ISSUE THREAD

**Issue by hmaskell** [TabulaRasaDV/TRDV-Escape#9]
In Edit Contact state, there should be a Delete Contact button at the bottom.

![Edit Contact](https://user-images.githubusercontent.com/23707057/87484321-b7822400-c5ea-11ea-8cd4-90aa03735678.png)

**Comment by riya-kumari** [comment]
Does this work instead? I could add the delete contact button in edit contact as well.
<img width="375" alt="Screen Shot 2020-07-20 at 2 58 22 PM" src="https://user-images.githubusercontent.com/59320441/87990753-7631be80-ca99-11ea-9357-0fc4af13215e.png">

**Comment by hmaskell** [comment]
Not sure what we're looking at here. Are these proposed buttons triggered by a swipe gesture on an individual contact (if it existed)? Otherwise looks like there is nothing to edit or delete here.

**Comment by riya-kumari** [comment]
Yes, you swipe the contact to either edit or delete it. The contact name's hidden when you swipe to the right. Still working on that part.

**Comment by hmaskell** [comment]
Neat idea! Here's a mockup for it.
I think you should be able to swipe from right to left anywhere on the whole contact row to see these options, and swipe left to right on that contact to dismiss them. If you swipe left on any other contact, the previously swiped item should return to its normal no-buttons state (so that at any given time only one item has edit / delete buttons on the right). Also if you tap a contact to enter view state, these options should close.

![Contacts List - Swipe](https://user-images.githubusercontent.com/23707057/88105424-bdcb4f80-cb58-11ea-8b03-8ae5b18ad928.png)
